### ISSUE TITLE
varints license

### ISSUE THREAD

**Issue by matchaxnb** [dowski/misc#1]
Hi dowski,

The varints.py code has no license. Shall I consider it MIT/BSD/PD ? I use it for this : https://github.com/AtastaChloe/pyiwa (MIT license)

**Comment by dowski** [comment]
Yes, MIT is fine. Glad you found it useful. And sorry I just noticed this now. My Github notification settings were apparently set to not email me on new issues for my own repos.

**Comment by dowski** [comment]
Just uploaded BSD license. Probably doesn't matter to you, but just noting here for posterity.
